### ISSUE TITLE
Error in how summary.CV.SuperLearner extracts method

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#31]
Hi,

There seems to be an error with how summary.CV.SuperLearner attempts to determine the meta-learner method from its original call. The [first line](https://github.com/ecpolley/SuperLearner/blob/master/R/summary.CV.SuperLearner.R#L2) of summary.CV.SuperLearner is the issue:

```{r}
  method <- ifelse(is.null(as.list(object$call)[["method"]]), "method.NNLS", as.list(object$call)[["method"]])  # default is "method.NNLS"
```

This works if CV.SuperLearner is called with the default method, or if the method is specified directly in the call to CV.SuperLearner. But if the method is passed based on a variable then match.call() will not provide the method as a string value, and summary.CV.SuperLearner will return an error. One solution would be to modify CV.SuperLearner to explicitly save the value of the method argument as another element in its return object.

Here is code to reproduce the error:

```{r}
library(SuperLearner)
library(glmnet)

set.seed(1)
N = 200
X = as.data.frame(matrix(rnorm(N*10), N, 10))
Y = rbinom(N, 1, plogis(.2*X[, 1] + .1*X[, 2] - .2*X[, 3] + .1*X[, 3]*X[, 4] - .2*abs(X[, 4])))

sl_lib = c("SL.glmnet", "SL.mean")

method = "method.NNLS"
test_nnls = CV.SuperLearner(Y = Y, X = X, SL.library = sl_lib, V=3, method = method, family = binomial())
summary(test_nnls)
# Error in match(x, table, nomatch = 0L) : 
#  'match' requires vector arguments
test_nnls$call
# CV.SuperLearner(Y = Y, X = X, V = 3, family = binomial(), SL.library = sl_lib, 
#    method = method)
as.list(test_nnls$call)[["method"]]
# method

# This version will be fine:
test_nnls2 = CV.SuperLearner(Y = Y, X = X, SL.library = sl_lib, V=3, method = "method.NNLS", family = binomial())
summary(test_nnls2)
```

Thanks,
Chris

**Comment by ecpolley** [comment]
Thanks, I realize my help documents for this are wrong. It states, `method` "A list (or a function to create a list) containing details..." and then I supply a character string as the default. In my own terrible defense, `SuperLearner` does work if you follow the documentations and give a function or a list, but you are right that `summary.CV.SuperLearner` fails.

My first thought is to add `as.character(...)` in that first line of `summary.CV.SuperLearner()` will at least fix those cases when the user follows the documentation (which I'll also clarify). This won't fix your case since you are passing a named symbol as the method. In your example, adding 
    
    method <- if(is.symbol(as.list(test_nnls$call)[["method"]])) get(paste(as.list(test_nnls$call)[["method"]]))

Will resolve for those cases when the symbol is one of the predefined methods, but a long range solution will also be to return a better summary for when the user isn't using one of the pre-defined methods.

**Comment by ck37** [comment]
Gotcha, yup sounds good to me - I have not run into get() before so that line of code is helpful. Agreed that supporting custom methods would be handy too.
